# Generated by Django 2.2.6 on 2019-10-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('descr', models.CharField(max_length=200)),
                ('date', models.IntegerField()),
            ],
        ),
    ]
